/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function getXchaCha20Poly1305Cipher(key: Buffer): object
export function encrypt(jsCipher: object, nonce: Buffer, plaintext: Buffer): Buffer
export function decrypt(jsCipher: object, nonce: Buffer, ciphertext: Buffer): Buffer
